server:
  port: 8081

spring:
  http:
    encoding.force: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

  profiles:
    active: #profile#
  liquibase:
    change-log: classpath:/db/master.xml
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_schema: public
        format_sql: true
        jdbc.time_zone: UTC
        org.hibernate.envers.audit_table_suffix: _aud
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    database: POSTGRESQL
    generate-ddl: false
    show-sql: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:15432/auth
    username: postgres
    password: postgres
    # hiraki:
    #  minimumIdle: 5
    #  maximumPoolSize: 20
    #  idleTimeout: 30000
    #  poolName: FinanceiroHirakiCP
    #   maxLifetime: 2000000
    #   connectionTimeout: 30000

